Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/xenial64"

	#add a private network between localhost & VM using ip
	config.vm.network "private_network", ip: "192.168.10.100"

	#copy provision file over
	config.vm.provision "file", source: "./provision.sh", destination: "$HOME/"

	#copy over nginx config
	config.vm.provision "file", source: "./default", destination: "$HOME/"

	#gives the provison.sh file ablity to execute
	config.vm.provision "shell", inline: "sudo chmod +x provision.sh"

	#Runs the file
	config.vm.provision "shell", inline: "sudo ./provision.sh"

	#Can run the provision file from local with: config.vm.provision "shell", path: "provision.sh"

	# Synced app folder
	# cp everything from current location create a folder called app - copy everything from localhost
	config.vm.synced_folder "./app", "/home/vagrant/app"


end