
# -*- mode: ruby -*-
 # vi: set ft=ruby :
 
 # All Vagrant configuration is done below. The "2" in Vagrant.configure
 # configures the configuration version (we support older styles for
 # backwards compatibility). Please don't change it unless you know what
 
 # MULTI SERVER/VMs environment 
 #
Vagrant.configure("2") do |config|
# creating our Ansible controller

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.define "controller" do |controller|
      
    controller.vm.box = "bento/ubuntu-18.04"
    
    controller.vm.hostname = 'controller'
    
    controller.vm.network :private_network, ip: "192.168.33.12"

    #copy provision file over
    controller.vm.provision "file", source: "controller_pro.sh", destination: "$HOME/"

    #gives the provison.sh file ablity to execute
    controller.vm.provision "shell", inline: "sudo chmod +x controller_pro.sh"

    #Runs the file
    controller.vm.provision "shell", inline: "sudo ./controller_pro.sh"
  end
end